# Generated by Django 5.1.6 on 2025-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='uploded_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
